#!/bin/bash
#operating system:  CentOS 6.x
# git clone https://github.com/357724264/initServer.git
software_path=/data/
install_path=/usr/local/

#yum install jdk-1.8
jdk() {
	#wget -P $software_path --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz
    [ -d  /usr/java ] || mkdir -p /usr/java
    cp $software_path/jdk-8u111-linux-x64.tar.gz  /usr/java/
    tar -zvxf  /usr/java/jdk-* -C /usr/java/
    cat ./data/javaEnvironment >> /etc/profile
}

#yum install redis
install_redis() {
    yum install tcl
  
	# wget http://download.redis.io/releases/redis-3.2.8.tar.gz
	[ -d  $install_path/redis ] || mkdir -p $install_path/redis
	tar -zvxf  $software_path/redis-* -C $install_path/redis/
	cd $install_path/redis/redis-*/
	dir
	make
    make test
    make install

}

#yum install nginx



#yum install mysql	CentOS 6.x
install_mysql() {

	wget https://repo.mysql.com//mysql57-community-release-el6-10.noarch.rpm
	sudo rpm -Uvh mysql57-community-release-el6-10.noarch.rpm

    ### start install
	yum repolist all | grep mysql
	yum repolist enabled | grep mysql
	sudo yum install mysql-community-server
	sudo service mysqld start
	sudo service mysqld status

	#mysql -uroot -p 

}


#yum install mosquitto
mosquitto() {
	#配置yum
    cp ./data/mosquitto.repo  /etc/yum.repos.d/
	yum install mosquitto mosquitto-clients
	service mosquitto start
}
#wget download tomcat
tomcat() {
	wget -P $software_path https://mirrors.aliyun.com/apache/tomcat/tomcat-8/v8.5.14/bin/apache-tomcat-8.5.14.tar.gz

	[ -d  $install_path/tomcat ] || mkdir -p $install_path/tomcat
	tar -zvxf  $software_path/apache-tomcat-* -C $install_path/tomcat/
}


start(){
	#mosquitto;
	jdk;
	tomcat;
}

testFun() {
	install_redis;

}

case "$1" in
	start )
		start;;
	mosquitto)
        mosquitto;;
    test)
        testFun;;
		*)
        echo "Usage: $0 {start|mosquitto}"
            exit 1
esac
exit 0