#!/bin/bash
#operating system:  CentOS 6.x
# git clone https://github.com/357724264/initServer.git
software_path=/data/
install_path=/usr/local/



start_redis() {
	#/usr/local/redis-*/src/redis-server&
    /usr/local/redis/redis-*/src/redis-server&
    sleep 3s
    echo success
    #/usr/local/redis-*/src/redis-sentinel sentinel.conf&
    /usr/local/redis/redis-*/src/redis-sentinel ../sentinel.conf&
    sleep 3s
    echo success
#./redis-sentinel sentinel.conf
}

start_zookeeper() {
	#/usr/local/zookeeper/zookeeper-*/bin/zkServer.sh start
	/usr/local/zookeeper/zookeeper-*/bin/zkServer.sh start
	sleep 3s
	echo success
}

activemq() {
	#/usr/local//activemq/apache-activemq-*/bin/activemq start
	/usr/local/activemq/apache-activemq-*/bin/activemq start
	sleep 3s
	echo success
	# /root/apache-activemq-5.14.0/bin/activemq start
}

start_dubbo-monitor-simple() {
	#/usr/local/dubbo/monitor/dubbo-monitor-simple/bin/start.sh
	/usr/local/dubbo/monitor/dubbo-monitor-simple/bin/start.sh
}

start_nginx() {
	#/usr/local/dubbo/monitor/dubbo-monitor-simple/bin/start.sh
	/usr/local/nginx/sbin/nginx -s reload
}



all(){
	start_redis;
	start_zookeeper;
	start_activemq;
}

testFun() {
	install_zookeeper;
}

case "$1" in
	all )
		all;;
    test)
        testFun;;
		*)
        echo "Usage: $0 {all|mosquitto}"
            exit 1
esac
exit 0